CREATE TABLE IF NOT EXISTS b_sharov_sc_car (
    ID INT NOT NULL AUTO_INCREMENT,
    CONTACT_ID INT NOT NULL,
    BRAND VARCHAR(100) NOT NULL,
    MODEL VARCHAR(100) NOT NULL,
    LICENSE_PLATE VARCHAR(30) NOT NULL,
    YEAR INT NULL,
    COLOR VARCHAR(50) NULL,
    MILEAGE INT NULL,
    VIN VARCHAR(50) NULL,
    DATE_CREATE DATETIME NOT NULL,
    DATE_UPDATE DATETIME NULL,
    PRIMARY KEY (ID),
    INDEX IX_SHAROV_SC_CAR_CONTACT_ID (CONTACT_ID),
    INDEX IX_SHAROV_SC_CAR_LICENSE_PLATE (LICENSE_PLATE)
);